# This is the configuration file for the plugin.
syn:

  # Door open setting
  # if true, allow everyone to enter the server, except for players on the ban list
  # if false, allow the player in the allowlist to come into the server.
  # The default value is false
  open: false

  # The available characters for the verification code
  # The length requires to be 10 or more
  # NOTE: If you remove some characters, may cause the old verification code invalid
  #       Because the old verification code may contain the removed characters
  # The default value is "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  available_characters: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

  # The website to show the verification code in game chat
  # If you don't want to show the verification code, you can set it to ""
  # The default value is "https://rock-mc.com/code/?text="
  show_code_url: "https://rock-mc.com/code/?text="

  # The length of the verification code
  # The length requires to be 4 or more
  # The default value is 6
  code_length: 6

  # The expiration time of the verification code
  # 0 means the verification code will never expire
  # The default value is 14
  expire_days: 14

  # The max wait time of the input verification code
  # The default value is 60
  max_wait_input_code_seconds: 60

  # The max times of the input verification code
  # The default value is 3
  max_input_code_times: 3

  # The ban time of the player who input the wrong verification code too many times
  # The default value is 1
  input_code_ban_days: 1

  # The clear time of the expired verification code
  # 0 means the verification code will never clear
  # It make sure the verification code will not be repeated in clear_days.
  # The default value is 365
  clear_days: 365

  # Database setting
  database:
      # The database type, currently only support sqlite
      # The default value is sqlite
      type: sqlite
